#!/usr/bin/env python
#
# rebuildd-job-add - Add a job to rebuildd
#
# (c) 2007 - Julien Danjou <acid@debian.org>
#
#   This software is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; version 2 dated June, 1991.
#
#   This software is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this software; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

from rebuildd.Rebuildd import Rebuildd
from rebuildd.RebuilddConfig import RebuilddConfig
import sqlobject, sys

def connect_db():
    sqlobject.sqlhub.processConnection = \
        sqlobject.connectionForURI(RebuilddConfig().get('build', 'database_uri'))

for line in sys.stdin.readlines():
    args = line.strip().split(' ')
    if len(args) == 3:
        Rebuildd().add_job(args[0], args[1], args[2])
    if len(args) == 4:
        Rebuildd().add_job(args[0], args[1], args[2], mailto=None, arch=args[3])
    if len(args) == 5:
        Rebuildd().add_job(args[0], args[1], args[2], mailto=args[4], arch=args[3])
else:
    print "E: usage: %s\n   read <package> <version> <dist> [arch] [mailto] from stdin" % sys.argv[0]
    sys.exit(1)
