#! /bin/bash

# Exit on errors
set -e

# Use pbuilder by default
PBUILDER_BIN="/usr/sbin/pbuilder"
PBUILDER_CACHE_PATH="/var/cache/pbuilder"
PBUILDER_MIRROR="http://ftp.debian.org/debian"

if [ -f /etc/default/rebuildd ]
then
    unset PBUILDER_BIN
    . /etc/default/rebuildd
fi

test "$ENABLE_BUILDER_MAINT" = 0 && exit 0

pbuilder_update()
{
        if [ ! -x "$PBUILDER_BIN" ]
        then
            echo "E: pbuilder not found: $PBUILDER_BIN"
            exit 1
        fi

        echo "I: Updating pbuilder for $DISTS"
        for d in $DISTS
        do
            for a in $ARCHS
            do
                $PBUILDER_BIN update --basetgz $PBUILDER_CACHE_PATH/${d}-${a}.tgz
            done
        done
}


cowbuilder_update()
{
        if [ ! -x "$COWBUILDER_BIN" ]
        then
            echo "E: cowbuilder not found: $COWBUILDER_BIN"
            exit 1
        fi

        echo "I: Updating cowbuilder for $DISTS"
        for d in $DISTS
        do
            for a in $ARCHS
            do
                $COWBUILDER_BIN --update --basepath $PBUILDER_CACHE_PATH/${d}-${a}.cow
            done
        done
}


if [ ! -z "$COWBUILDER_BIN" ]
then
    cowbuilder_update
else
    pbuilder_update
fi
